## Write a Numpy program to compute the multiplication of two given matrixes

In [7]:
import numpy as np
from numpy import linalg
a = np.array([[1, 5], [2, 6]])
b = np.array([[4, 8], [3, 7]])
result = np.dot(a, b)
print(result)

[[19 43]
 [26 58]]


## Write a NumPy program to compute the determinant of a given square array

In [8]:
a = np.array([[5, 6], [7, 8]])
print(np.linalg.det(a))

-1.999999999999999


## Write a NumPy program to compute the cross product of two given vectors

In [13]:
a=np.array([[1, 5]])
b=np.array([[4, 8]])
result=np.cross(a, b)
print(result)

[-12]


## Write a NumPy program to compute the condition number of a given matrix

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b=linalg.cond(a)
print(b)

1.201149133689022e+17


## Write a NumPy program to compute the inverse of a given matrix

In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
result =  np.linalg.inv(my_matrix)
print(result)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
